### ISSUE TITLE
Terminate script if there is no successful connection to the MQTT Broker

### ISSUE THREAD

**Issue by daschubert** [SiegelDaniel/MQTT-IDS#17]
When executing tracing.py without a running mosquitto instance on AGL, the scripts continues to process after `ConnectionRefusedError`
```
INFO:root:MQTT Client instantiated
Starting tracing
INFO:root:Started polling
INFO:root:Traced:547, now publishing
Traceback (most recent call last):
  File "tracing.py", line 144, in <module>
    client.connect(BROKER_IP)
  File "/usr/lib/python3.5/site-packages/paho/mqtt/client.py", line 760, in connect
    return self.reconnect()
  File "/usr/lib/python3.5/site-packages/paho/mqtt/client.py", line 887, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/lib/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
INFO:root:Parsed trace from: 547 to XML
INFO:root:Sucessfully sent:
<trace_data><pinfo>547</pinfo><trace>strace: Process 547 attached
</trace></trace_data>
via Topic 'TRACED'
INFO:root:Traced:547, now publishing
INFO:root:Parsed trace from: 547 to XML
```

**Comment by SiegelDaniel** [comment]
Implemented in 4ba9300e161f84224cb9fb641ea45f64cb49bea5, line 159.
